#!/bin/bash
./makePrajitOS hammerhead
read -n1 -rsp "Press space to continue..." key
if [ "$key" = '' ]; then
    	# Space pressed, do something
    	# echo [$key] is empty when SPACE is pressed # uncomment to trace
	./makePrajitOS bullhead
#else
    	# Anything else pressed, do whatever else.
    	# echo [$key] not empty
fi
read -n1 -rsp "Press space to continue..." key
if [ "$key" = '' ]; then
	./makePrajitOS victara
fi
read -n1 -rsp "Press space to continue..." key
if [ "$key" = '' ]; then
	./makePrajitOS shamu
fi
read -n1 -rsp "Press space to continue..." key
if [ "$key" = '' ]; then
	./makePrajitOS mako
fi
