#!/bin/bash
read -n1 -rsp "Connect hammerhead and press space to continue..." key
if [ "$key" = '' ]; then
	./makePrajitOS hammerhead
fi
read -n1 -rsp "Connect bullhead and press space to continue..." key
if [ "$key" = '' ]; then
	./makePrajitOS bullhead
fi
read -n1 -rsp "Connect victara and press space to continue..." key
if [ "$key" = '' ]; then
	./makePrajitOS victara
fi
read -n1 -rsp "Connect shamu and press space to continue..." key
if [ "$key" = '' ]; then
	./makePrajitOS shamu
fi
read -n1 -rsp "Connect mako and press space to continue..." key
if [ "$key" = '' ]; then
	./makePrajitOS mako
fi
read -n1 -rsp "Connect maguro and press space to continue..." key
if [ "$key" = '' ]; then
	./makePrajitOS maguro
fi
read -n1 -rsp "Connect sailfish and press space to continue..." key
if [ "$key" = '' ]; then
	./makePrajitOS sailfish
fi
